const chars = "BCDFGHJKLMNPQRSTVWXYZbdfghjnqrt012345678-+÷π=%<>~$:\"?!↓↑*#♪★♠♦♣♥";
const biggestPossibleChar = chars.length - 1;

const specialChars = {
    "division": 42,
    "÷": 42,
    42: "÷",
    "pi": 43,
    "π": 43,
    43: "π",
    "arrowDown": 54,
    "↓": 54,
    54: "↓",
    "arrowUp": 55,
    "↑": 55,
    55: "↑",
    "note": 58,
    "♪": 58,
    58: "♪",
    "star": 59,
    "★": 59,
    59: "★",
    "spades": 60,
    "♠": 60,
    60: "♠",
    "diamonds": 61,
    "♦": 61,
    61: "♦",
    "clubs": 62,
    "♣": 62,
    62: "♣",
    "hearts": 63,
    "♥": 63,
    63: "♥",
};

const victoryStates = [
    { value: 0, label: "Defeat" },
    { value: 1, label: "Draw" },
    { value: 2, label: "Win" }
];

const teams = [
    { value: 0,  label: "Italy" },
    { value: 1,  label: "Holland" },
    { value: 2,  label: "England" },
    { value: 3,  label: "Norway" },
    { value: 4,  label: "Spain" },
    { value: 5,  label: "Ireland" },
    { value: 6,  label: "Portugal" },
    { value: 7,  label: "Denmark" },
    { value: 8,  label: "Germany" },
    { value: 9,  label: "France" },
    { value: 10, label: "Belgium" },
    { value: 11, label: "Sweden" },
    { value: 12, label: "Romania" },
    { value: 13, label: "Bulgaria" },
    { value: 14, label: "Russia" },
    { value: 15, label: "Swiss" },
    { value: 16, label: "Greece" },
    { value: 17, label: "Croatia" },
    { value: 18, label: "Austria" },
    { value: 19, label: "Wales" },
    { value: 20, label: "Scotland" },
    { value: 21, label: "N. Ireland" },
    { value: 22, label: "The Czech Rep." },
    { value: 23, label: "Poland" },
    { value: 24, label: "Japan" },
    { value: 25, label: "S. Korea" },
    { value: 26, label: "Turkey" },
    { value: 27, label: "Nigeria" },
    { value: 28, label: "Cameroon" },
    { value: 29, label: "Morocco" },
    { value: 30, label: "Brazil" },
    { value: 31, label: "Argentina" },
    { value: 32, label: "Columbia" },
    { value: 33, label: "Mexico" },
    { value: 34, label: "USA" },
    { value: 35, label: "Uruguay" },
    { value: 36, label: "All Star" },
    { value: 37, label: "Eurostar.a" },
    { value: 38, label: "Eurostar.b" },
    { value: 39, label: "Asian star" },
    { value: 40, label: "AfricanStar" },
    { value: 41, label: "AllAmericanStar" }
];

